- name: check mode demo
  hosts: all
  tasks:
    - name: create a file
      file:
        path: ~/Desktop/file1
        state: touch
    - name: create a second file
      file:
        path: ~/Desktop/file2
        state: touch
      check_mode: yes
    - name: create a third file
      file:
        path: ~/Desktop/file3
        state: touch
      check_mode: no
